---
- name: Check filter module
  hosts: all
  remote_user: vagrant

  tasks:
    - name: Get a couple of facts from the host
      debug:
        var: "{{ item }}"
      with_items:
        - "ansible_ssh_user"
        - "ansible_distribution"
        - "ansible_distribution_release"

