---
- name: Install ruby and ruby-dev
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - "{{ ruby_package }}"
    - "{{ ruby_package }}-dev"

- name: Install additional packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items: ruby_additional_packages

- name: Update ruby alternative
  alternatives:
    name: "ruby"
    link: "/usr/bin/ruby"
    path: "/usr/bin/{{ ruby_package }}"

- name: Update gem alternative
  alternatives:
    name: "gem"
    link: "/usr/bin/gem"
    path: "/usr/bin/{{ ruby_package | replace('ruby', 'gem') }}"

- name: Install bundler
  gem:
    name: bundler
    user_install: no
    state: present

