---
- name: Deploy TODO application
  hosts: webservers
  sudo: yes

  tasks:
    - name: Install ruby and build dependencies
      apt:
        name: "{{ item }}"
        update_cache: yes
        cache_valid_time: 3600
        state: installed
      with_items:
        - ruby2.0
        - ruby2.0-dev
        - git
        - build-essential
        - libsqlite3-dev

    - name: Update ruby and gem alternatives
      alternatives:
        name: "{{ item }}"
        link: "/usr/bin/{{ item }}"
        path: "/usr/bin/{{ item }}2.0"
      with_items:
        - ruby
        - gem

    - name: Install bundler
      gem:
        name: bundler
        user_install: no
        state: present

    - name: Add user
      user:
        name: web
        home: /var/www
        createhome: yes
        system: yes
        state: present

    - name: Clone repository
      git:
        repo: https://github.com/timmillwood/todo_list
        dest: /var/www/todo
        version: master
      sudo_user: web
      register: source
      notify: Restart todo app

    - name: Bundle install
      command: bundle install --path vendor/bundle
      args:
        chdir: /var/www/todo
      sudo_user: web
      when: source.changed
      notify: Restart todo app

    - name: Add init script
      copy:
        src: files/todo.conf
        dest: /etc/init/todo.conf
        owner: root
        group: root
        mode: 0755

    - name: Enable service
      service:
        name: todo
        enabled: yes

  handlers:
    - name: Restart todo app
      service:
        name: todo
        state: restarted

